openapi: 3.0.1
info:
  title: Shopping List
  description: ShoppingList Interface
  version: 1.0.0
servers:
  - url: 'https://{host}/{version}'
    variables:
      host:
        default: sl.test.devloop.de
      version:
        default: v1
tags:
  - name: Shopping List
    description: Shopping List operations
  - name: Shopping Item
    description: Shopping Item operations
  - name: Store Item
    description: Store Item operations
paths:
  /shoppingLists:
    get:
      tags:
        - Shopping List
      summary: get all Shopping Lists
      operationId: getShoppingLists
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShoppingList'
      security:
        - basicAuth: []
  /shoppingList:
    get:
      tags:
        - Shopping List
      summary: get one Shopping List
      operationId: getShoppingList
      parameters:
        - name: shoppingListId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShoppingList'
        '400':
          description: Invalid Input
          content: {}
      security:
        - basicAuth: []
    put:
      tags:
        - Shopping List
      summary: add new Shopping List
      operationId: addShoppingList
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/ShoppingList'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ShoppingList'
        '400':
          description: Invalid Input
          content: {}
      security:
        - basicAuth: []
      x-codegen-request-body-name: body
    delete:
      tags:
        - Shopping List
      summary: remove Shopping List
      operationId: removeShoppingList
      parameters:
        - name: shoppingListId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content: {}
        '400':
          description: Invalid Input
          content: {}
      security:
        - basicAuth: []
  /shoppingItems:
    get:
      tags:
        - Shopping Item
      summary: get all Shopping Items of Shopping List
      operationId: getShoppingItems
      parameters:
        - name: shoppingListId
          in: query
          required: true
          schema:
            type: integer
        - name: bySortKey
          in: query
          description: return list sorted by SortKey of StoreItem - false if not present
          schema:
            type: boolean
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShoppingItem'
        '400':
          description: Invalid Input
          content: {}
      security:
        - basicAuth: []
  /shoppingItem:
    put:
      tags:
        - Shopping Item
      summary: add new Shopping Item
      operationId: addShoppingItem
      parameters:
        - name: shoppingListId
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/ShoppingItem'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ShoppingItem'
        '400':
          description: Invalid Input
          content: {}
      security:
        - basicAuth: []
      x-codegen-request-body-name: body
    delete:
      tags:
        - Shopping Item
      summary: remove Shopping Item from Shopping List
      operationId: removeShoppingItem
      parameters:
        - name: shoppingItemId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content: {}
        '400':
          description: Invalid Input
          content: {}
      security:
        - basicAuth: []
  /storeItems:
    get:
      tags:
        - Store Item
      summary: get/search all Store Items
      operationId: getStoreItems
      parameters:
        - name: text
          in: query
          description: >-
            return only Store Items matching `text` - matching all if not
            present
          schema:
            type: string
        - name: limit
          in: query
          description: return only `limit` numbers of Store Items - no limit if not present
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StoreItem'
        '400':
          description: Invalid Parameters
          content: {}
      security:
        - basicAuth: []
  /storeItems/recalculateSortKey:
    get:
      tags:
        - Store Item
      summary: rebase sort key of all Sort Items
      operationId: recalculateStoreItemSort
      responses:
        '200':
          description: successful operation
          content: {}
      security:
        - basicAuth: []
  /storeItem:
    put:
      tags:
        - Store Item
      summary: add new Store Item
      operationId: addStoreItem
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/StoreItem'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/StoreItem'
        '400':
          description: Invalid Input
          content: {}
      security:
        - basicAuth: []
      x-codegen-request-body-name: body
    post:
      tags:
        - Store Item
      summary: update existing Store Item
      operationId: updateStoreItem
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/StoreItem'
        required: true
      responses:
        '200':
          description: successful operation
          content: {}
        '400':
          description: Invalid Input
          content: {}
      security:
        - basicAuth: []
      x-codegen-request-body-name: body
components:
  schemas:
    ShoppingList:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        items:
          nullable: true
          type: array
          items:
            $ref: '#/components/schemas/ShoppingItem'
    ShoppingItem:
      type: object
      properties:
        id:
          type: integer
        shoppingListId:
          type: integer
        storeItemId:
          type: integer
        storeItem:
          $ref: '#/components/schemas/StoreItem'
        amount:
          type: integer
        unit:
          type: string
    StoreItem:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        unit:
          type: string
        sortKey:
          type: integer
          format: uint
          nullable: true
        barcode:
          type: string
          nullable: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
